import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { RefreshCw } from "lucide-react";
import { api } from "../lib/api";
import TrustBadge from "../components/TrustBadge";
import TypewriterText from "../components/TypewriterText";

export default function Insights() {
  const [summary, setSummary] = useState<string | null>(null);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generate = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await api.generateInsights();
      setSummary(res.summary);
      setGeneratedAt(res.generatedAt);
    } catch {
      setError(
        "Couldn't reach the AI service — make sure the backend is running with an GEMINI_API_KEY set."
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35 }}>
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-ink">Insights</h1>
          <p className="text-sm text-slate-500">Your week, explained in plain language.</p>
        </div>
        <TrustBadge kind="ai" label="Generated by Gemini, on demand" />
      </div>

      <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
        <div className="mb-4 flex items-center justify-between">
          <h2 className="font-semibold text-ink">
            {generatedAt ? `As of ${new Date(generatedAt).toLocaleString()}` : "No summary yet"}
          </h2>
          <motion.button
            whileTap={{ scale: 0.97 }}
            onClick={generate}
            disabled={loading}
            className="flex items-center gap-2 rounded-lg bg-brand px-4 py-2 text-sm font-medium text-white shadow-sm transition-colors hover:bg-brand-dark disabled:opacity-50"
          >
            <RefreshCw size={14} className={loading ? "animate-spin" : ""} />
            {loading ? "Analyzing…" : summary ? "Regenerate" : "Generate this week's insight"}
          </motion.button>
        </div>

        {error && <p className="text-sm text-danger">{error}</p>}

        {!error && !summary && !loading && (
          <p className="text-sm text-slate-400">
            Click generate — this pulls your brand's real activity log and asks Gemini to
            summarize it, live.
          </p>
        )}

        <AnimatePresence>
          {summary && (
            <motion.p
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              className="text-sm leading-relaxed text-slate-700"
            >
              <TypewriterText text={summary} speed={10} />
            </motion.p>
          )}
        </AnimatePresence>
      </div>

      <div className="mt-4 rounded-xl border border-dashed border-slate-300 p-5 text-sm text-slate-500">
        In production this runs automatically every Monday morning — the button here is
        just so you can see it happen on demand.
      </div>
    </motion.div>
  );
}
